// WordGrid Master — word bank
// Curated common-English words grouped into 5 tiers (A1 -> C1) with short definitions.
// This is a hand-curated subset (not the full 7,000-word list referenced in the spec);
// see the note at the end of this response for why, and how to extend it.
const WORD_BANK = {
  1: [ // A1 - Starter (most frequent, everyday words)
    ["time","a period that passes"],["day","24 hours"],["year","365 days"],["people","more than one person"],
    ["way","a method or path"],["man","an adult male"],["woman","an adult female"],["child","a young person"],
    ["world","the whole earth"],["life","being alive"],["hand","end of your arm"],["eye","organ for seeing"],
    ["house","a place to live"],["water","clear liquid you drink"],["food","what you eat"],["family","parents and children"],
    ["friend","someone you like and trust"],["school","place where you learn"],["work","a job or task"],
    ["book","pages with words"],["car","a vehicle you drive"],["city","a large town"],["money","used to buy things"],
    ["phone","device for calling"],["color","red, blue, green etc"],["animal","a living creature"],
    ["dog","a common pet that barks"],["cat","a common pet that meows"],["tree","a tall plant with a trunk"],
    ["sun","star that lights the day"],["moon","object seen at night"],["star","light in the night sky"],
    ["sky","space above the earth"],["rain","water falling from clouds"],["snow","frozen white rain"],
    ["wind","moving air"],["fire","hot burning flame"],["earth","the planet we live on"],["air","what we breathe"],
    ["love","strong caring feeling"],["happy","feeling good"],["sad","feeling unhappy"],["big","large in size"],
    ["small","little in size"],["fast","quick"],["slow","not fast"],["hot","high temperature"],
    ["cold","low temperature"],["new","not old"],["old","not new"],["good","of high quality"],
    ["bad","not good"],["easy","not difficult"],["hard","difficult"],["open","not closed"],
    ["close","to shut"],["start","to begin"],["stop","to end an action"],["buy","to pay for something"],
    ["sell","to give for money"],["eat","to consume food"],["drink","to consume liquid"],
    ["sleep","to rest at night"],["walk","to move on foot"],["run","to move quickly on foot"],
    ["talk","to speak"],["listen","to pay attention to sound"],["read","to look at and understand text"],
    ["write","to put words on paper"],["think","to use your mind"],["know","to have information"],
    ["want","to desire"],["need","to require"],["like","to enjoy"],["give","to hand over"],
    ["take","to grab or receive"],["make","to create"],["find","to discover"],["look","to see"],
    ["hear","to notice sound"],["feel","to sense"],["ask","to question"],["answer","a reply"],
    ["help","to assist"],["play","to have fun"],["live","to exist"],["move","to change place"],
    ["stay","to remain"],["come","to arrive"],["go","to leave"],["door","entrance to a room"],
    ["window","glass opening in a wall"],["table","furniture with a flat top"],["chair","furniture to sit on"],
    ["bed","furniture to sleep on"],["room","a section of a house"],["street","a road in a town"],
    ["shop","a place to buy things"],["morning","early part of the day"],["night","dark part of the day"],
    ["week","seven days"],["month","about thirty days"],["today","this day"],["tomorrow","the day after today"],
    ["yesterday","the day before today"],["number","a symbol like 1, 2, 3"],["name","what you are called"]
  ],
  2: [ // A2 - Basic
    ["reason","why something happens"],["result","what happens because of an action"],
    ["question","something you ask"],["problem","a difficult situation"],["idea","a thought"],
    ["plan","an arranged way to do something"],["group","a set of people or things"],["team","people working together"],
    ["business","buying and selling for profit"],["company","an organization that sells things"],
    ["market","a place to buy and sell"],["price","how much something costs"],["value","how useful or important"],
    ["quality","how good something is"],["service","help provided to someone"],["product","something made to sell"],
    ["customer","a person who buys"],["decision","a choice you make"],["chance","a possibility"],
    ["choice","an option you pick"],["experience","knowledge from doing something"],["skill","ability to do something well"],
    ["subject","a topic of study"],["education","the process of learning"],["knowledge","information you know"],
    ["language","a system of communication"],["culture","customs and beliefs of a group"],["history","past events"],
    ["society","people living together"],["government","the group that rules a country"],["country","a nation"],
    ["nation","a large group with shared identity"],["community","people in the same area"],
    ["environment","the natural world around us"],["nature","the physical world"],["weather","conditions like rain or sun"],
    ["season","spring, summer, autumn, winter"],["energy","power to do work"],["health","condition of the body"],
    ["medicine","treatment for illness"],["hospital","place to treat sick people"],["doctor","a medical professional"],
    ["patient","a person receiving treatment"],["disease","an illness"],["exercise","physical activity"],
    ["diet","the food you eat"],["sport","a physical game"],
    ["match","a sports contest"],["competition","a contest between people"],["victory","winning"],
    ["success","achieving a goal"],["failure","not succeeding"],["effort","hard work"],["progress","moving forward"],
    ["improve","to make better"],["develop","to grow or improve"],["achieve","to succeed at something"],
    ["increase","to become larger"],["decrease","to become smaller"],["reduce","to make less"],
    ["produce","to make something"],["create","to bring into existence"],["design","to plan how something looks"],
    ["build","to construct"],["repair","to fix"],["destroy","to break completely"],["protect","to keep safe"],
    ["support","to help"],["encourage","to give confidence"],["suggest","to propose an idea"],
    ["recommend","to advise something is good"],["explain","to make clear"],["describe","to say what something is like"],
    ["compare","to look at differences"],["discuss","to talk about"],["agree","to have the same opinion"],
    ["disagree","to have a different opinion"],["allow","to permit"],["prevent","to stop from happening"],
    ["avoid","to stay away from"],["continue","to keep doing"],
    ["complete","to finish"],["prepare","to get ready"],["organize","to arrange in order"],
    ["manage","to be in charge of"],["control","to have power over"],["direct","to guide"],
    ["lead","to be in front"],["follow","to go after"],["join","to become part of"],
    ["separate","to split apart"],["connect","to join together"],["depend","to rely on"],
    ["belong","to be part of a group"],["remember","to recall"],["forget","to fail to remember"],
    ["imagine","to picture in your mind"],["realize","to understand suddenly"]
  ],
  3: [ // B1 - Intermediate
    ["achievement","something accomplished successfully"],["ambition","a strong desire to succeed"],
    ["approach","a way of dealing with something"],["assumption","something believed without proof"],
    ["attitude","a way of thinking or feeling"],["attention","focused notice"],["authority","the power to control"],
    ["awareness","knowledge of a situation"],["balance","a state of equal weight"],["barrier","something blocking progress"],
    ["behavior","the way someone acts"],["benefit","an advantage"],["capacity","the ability to hold or do"],
    ["challenge","a difficult task"],["circumstance","a fact related to an event"],["commitment","a promise to do something"],
    ["concept","a general idea"],["condition","the state of something"],["confidence","belief in oneself"],
    ["conflict","a serious disagreement"],["consequence","a result of an action"],["contribution","something given to help"],
    ["controversy","a public disagreement"],["convenience","being easy to use"],["cooperation","working together"],
    ["criticism","pointing out faults"],["curiosity","a desire to learn"],["debate","a formal discussion"],
    ["dedication","commitment to a task"],["demand","a strong request"],["dependence","needing something"],
    ["determination","firmness of purpose"],["dimension","a measurable extent"],["discipline","controlled behavior"],
    ["distinction","a clear difference"],["diversity","a range of different things"],["efficiency","doing something well without waste"],
    ["element","a basic part of something"],["emphasis","special importance given"],["enthusiasm","strong excitement"],
    ["equality","being equal"],["establishment","an organization or institution"],["evidence","facts that prove something"],
    ["evolution","gradual development"],["exception","something excluded from a rule"],["expansion","becoming larger"],
    ["expectation","a strong belief something will happen"],["exposure","being subject to something"],
    ["expression","showing feelings or ideas"],["factor","something that influences a result"],
    ["feature","a distinctive part"],["flexibility","ability to adapt"],["foundation","the basis of something"],
    ["framework","a basic structure"],["function","the purpose of something"],["generation","people born in the same period"],
    ["genuine","real and authentic"],["guarantee","a firm promise"],["guidance","helpful advice"],
    ["harmony","peaceful agreement"],["hesitation","pausing before acting"],["hypothesis","a proposed explanation"],
    ["identity","who or what someone is"],["ignorance","lack of knowledge"],["illustration","an example that explains"],
    ["impact","a strong effect"],["implication","a possible consequence"],["incentive","something that motivates"],
    ["incident","an event, often unpleasant"],["independence","freedom from control"],["influence","the power to affect"],
    ["initiative","the ability to act first"],["insight","a deep understanding"],["inspiration","something that motivates creativity"],
    ["instinct","a natural tendency"],["institution","an established organization"],["integrity","being honest and whole"],
    ["intention","a plan or purpose"],["interaction","communication between people"],["interpretation","an explanation of meaning"],
    ["intuition","understanding without reasoning"],["investment","putting money to earn more"],
    ["involvement","being part of something"],["justification","a good reason for something"],["legacy","something left behind"],
    ["legitimate","allowed by law or rules"],["liability","legal responsibility"],["limitation","a restriction"],
    ["logic","reasoned thinking"],["maintenance","keeping something in good condition"],["motivation","a reason to act"],
    ["objective","a goal; not biased"],["obligation","a duty"],["obstacle","something blocking progress"],
    ["opportunity","a good chance"],["outcome","a result"],["participation","taking part in something"]
  ],
  4: [ // B2 - Upper-Intermediate
    ["abundance","a very large quantity"],["accountability","being responsible for actions"],["acquisition","gaining something"],
    ["adaptation","adjusting to new conditions"],["adversity","a difficult situation"],["aesthetic","concerned with beauty"],
    ["ambiguity","being unclear or having multiple meanings"],["ambivalent","having mixed feelings"],
    ["anomaly","something that deviates from the norm"],["anticipate","to expect something"],["apathy","lack of interest"],
    ["arbitrary","based on random choice"],["articulate","able to express clearly"],["assertive","confident and direct"],
    ["assimilate","to absorb and understand"],["attribute","a quality; to credit to a cause"],
    ["autonomous","independent, self-governing"],["boundary","a limit or dividing line"],["bureaucracy","a system of officials and procedures"],
    ["candor","honesty and openness"],["catalyst","something that causes change"],["coherent","logical and consistent"],
    ["coincide","to happen at the same time"],["collaborate","to work together"],["compelling","convincing"],
    ["comprehensive","complete and thorough"],["conceive","to form an idea"],["conform","to follow rules or norms"],
    ["consolidate","to combine into one"],["constraint","a limitation"],["contemplate","to think deeply"],
    ["contradict","to say the opposite"],["conventional","following accepted norms"],["convey","to communicate"],
    ["credible","believable"],["cumulative","increasing by successive additions"],["deficient","lacking something needed"],
    ["deliberate","done on purpose; to think carefully"],["derive","to obtain from a source"],["deviate","to depart from the norm"],
    ["diligent","showing careful effort"],["diminish","to make smaller"],["discrepancy","a difference between things"],
    ["disparity","a great difference"],["dissent","disagreement with an opinion"],["distinct","clearly different"],
    ["diverge","to separate and go different ways"],["dominant","most powerful or important"],["dubious","doubtful"],
    ["elaborate","detailed and complex"],["eloquent","fluent and persuasive in speaking"],["empirical","based on observation"],
    ["endorse","to publicly approve"],["enigmatic","mysterious and hard to understand"],["equivalent","equal in value"],
    ["erode","to gradually wear away"],["escalate","to increase rapidly"],["explicit","stated clearly"],
    ["exploit","to use for advantage"],["facilitate","to make easier"],["feasible","possible to do"],
    ["fluctuate","to change irregularly"],["fundamental","basic and essential"],["hierarchy","a system of ranks"],
    ["hinder","to make progress difficult"],["hypothetical","based on a possible idea"],["implicit","implied, not stated directly"],
    ["incentivize","to motivate with a reward"],["inevitable","certain to happen"],["infer","to conclude from evidence"],
    ["innovative","introducing new ideas"],["integral","essential to completeness"],["intricate","very detailed and complex"],
    ["intrinsic","belonging naturally to something"],["invoke","to call upon"],["irrational","not based on reason"],
    ["justify","to show something is right"],["legislation","laws collectively"],["mandate","an official order"],
    ["marginal","small and not very important"],["mitigate","to make less severe"],["momentum","force gained by movement"],
    ["negligible","too small to matter"],["notion","a belief or idea"],["notwithstanding","despite"],
    ["nuance","a subtle difference"],["obsolete","no longer used"],
    ["paradox","a statement that seems contradictory"],["paramount","more important than anything else"],
    ["perceive","to become aware of"],["perpetual","never ending"],["pervasive","spreading widely"],
    ["plausible","reasonable and believable"],["precedent","an earlier example used as a guide"],
    ["prevalent","widespread"],["proponent","a person who supports an idea"],["rationale","the reasons for a decision"],
    ["reciprocal","given in return"],["reinforce","to strengthen"],["resilient","able to recover quickly"],
    ["scrutinize","to examine closely"],["subsequent","coming after"],["substantial","large in amount"],
    ["undermine","to weaken gradually"],["viable","capable of working successfully"]
  ],
  5: [ // C1 - Advanced
    ["acumen","sharp insight and judgment"],["adjudicate","to make a formal judgment"],["aggregate","a total formed by combining parts"],
    ["alacrity","brisk, eager readiness"],["altruism","selfless concern for others"],["ambivalence","the state of having mixed feelings"],
    ["anachronistic","out of its proper time period"],["antithesis","the exact opposite"],["arbitrate","to settle a dispute"],
    ["archetype","a typical example of something"],["assiduous","showing great care and effort"],["austere","severe or plain in manner"],
    ["axiom","a statement accepted as true"],["belie","to give a false impression of"],["cacophony","a harsh mixture of sounds"],
    ["capitulate","to give in to demands"],["circumvent","to find a way around"],["cogent","clear and convincing"],
    ["conflate","to combine into one"],["congruent","in agreement or harmony"],["connote","to imply beyond the literal meaning"],
    ["contentious","causing disagreement"],["corroborate","to confirm with evidence"],["deferential","showing respect"],
    ["delineate","to describe precisely"],["demarcate","to set the boundaries of"],["deprecate","to express disapproval of"],
    ["didactic","intended to teach"],["disparate","essentially different"],["dogmatic","asserting opinions as facts"],
    ["ebullient","overflowing with enthusiasm"],["egregious","outstandingly bad"],["elicit","to draw out a response"],
    ["emulate","to imitate in order to equal"],["enervate","to weaken or drain of energy"],["ephemeral","lasting a very short time"],
    ["equanimity","calmness under pressure"],["equivocate","to use unclear language to avoid commitment"],
    ["esoteric","understood by only a few"],["exacerbate","to make a problem worse"],["exemplify","to be a typical example of"],
    ["exonerate","to clear from blame"],["extrapolate","to estimate by extending known data"],["fastidious","very attentive to detail"],
    ["fortuitous","happening by chance, luckily"],["gratuitous","uncalled for; unearned"],["hegemony","dominance over others"],
    ["heuristic","enabling learning through discovery"],["idiosyncrasy","a peculiar characteristic"],["impartial","not favoring one side"],
    ["imperative","extremely important, urgent"],["impetuous","acting without thought"],["incongruous","out of place"],
    ["indefatigable","untiring, persistent"],["indispensable","absolutely necessary"],["ineffable","too great to express in words"],
    ["ingenuous","innocent and unsuspecting"],["innate","inborn, natural"],["insidious","harmful in a gradual way"],
    ["intransigent","refusing to compromise"],["intrepid","fearless, adventurous"],["juxtapose","to place side by side for contrast"],
    ["laconic","using very few words"],["lucid","clearly expressed and easy to understand"],["magnanimous","generous in forgiving"],
    ["meticulous","showing extreme care over detail"],["myriad","a very large number"],["nascent","just beginning to develop"],
    ["nebulous","vague and unclear"],["obfuscate","to make unclear or confusing"],["obstinate","stubbornly refusing to change"],
    ["ostensible","stated as the reason but not necessarily so"],["paradigm","a typical pattern or model"],
    ["parochial","having a narrow, limited outlook"],["pertinent","relevant to the matter"],["pragmatic","dealing with things practically"],
    ["precarious","not securely held; risky"],["preclude","to prevent from happening"],["pretext","a false reason given to justify"],
    ["prolific","producing much in abundance"],["quintessential","representing the most perfect example"],
    ["recalcitrant","stubbornly resistant"],["repudiate","to reject as untrue"],["resolute","admirably determined"],
    ["sagacious","having good judgment"],["salient","most noticeable or important"],["sanguine","optimistic in a difficult situation"],
    ["scrupulous","very careful about details"],["sporadic","occurring at irregular intervals"],["stoic","enduring hardship without complaint"],
    ["surreptitious","done secretly"],["tacit","understood without being stated"],["tenuous","very weak or slight"],
    ["ubiquitous","present everywhere"],["unequivocal","leaving no doubt"],["vindicate","to clear of blame"],
    ["visceral","felt deeply, instinctive"],["vociferous","loud and forceful in expressing views"]
  ]
};

